apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::624699258127:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1CAY0CTCEZ9LD
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::624699258127:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
      - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-25T21:29:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "967"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 89b3fca8-a95a-4de8-bbe6-e1d55e1d4cfc
